apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastefy-app
  namespace: production
  labels:
    app: pastefy-app
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pastefy-app
  template:
    metadata:
      labels:
        app: pastefy-app
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "1337"
    spec:
      serviceAccountName: pastefy-app
      initContainers:
      - name: wait-for-db
        image: busybox:1.35.0
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        command: 
        - /bin/sh
        - -c
        - |
          echo "Waiting for MariaDB to be ready..."
          until nc -z pastefy-mariadb 3306; do
            echo "MariaDB not ready, waiting 5 seconds..."
            sleep 5
          done
          echo "MariaDB is ready!"
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: pastefy
        image: 475641479654.dkr.ecr.eu-west-2.amazonaws.com/pastefy-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 1337
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: HTTP_SERVER_PORT
          value: "1337"
        - name: DATABASE_DRIVER
          value: mysql
        - name: DATABASE_HOST
          value: pastefy-mariadb
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_NAME
          value: pastefy
        - name: DATABASE_USER
          value: pastefy
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pastefy-secrets
              key: mysql-password
        - name: SERVER_NAME
          value: "https://eks.integratepro.online"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 18
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: cache-volume
          mountPath: /app/cache
      volumes:
      - name: tmp-volume
        emptyDir:
          sizeLimit: 100Mi
      - name: cache-volume
        emptyDir:
          sizeLimit: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pastefy-app
  namespace: production
  labels:
    app: pastefy-app
spec:
  type: ClusterIP
  selector:
    app: pastefy-app
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pastefy-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pastefy-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pastefy-pdb
  namespace: production
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: pastefy-app
