apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production

---
apiVersion: v1
kind: Secret
metadata:
  name: pastefy-secrets
  namespace: production
type: Opaque
data:
  mysql-password: cGFzdGVmeQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastefy-app
  namespace: production
  labels:
    app: pastefy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pastefy-app
  template:
    metadata:
      labels:
        app: pastefy-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "1337"
    spec:
      containers:
      - name: pastefy
        image: 475641479654.dkr.ecr.eu-west-2.amazonaws.com/pastefy-app:latest
        ports:
        - containerPort: 1337
        env:
        - name: HTTP_SERVER_PORT
          value: "1337"
        - name: HTTP_SERVER_CORS
          value: "*"
        - name: DATABASE_DRIVER
          value: mysql
        - name: DATABASE_HOST
          value: pastefy-mariadb
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_NAME
          value: pastefy
        - name: DATABASE_USER
          value: pastefy
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pastefy-secrets
              key: mysql-password
        - name: SERVER_NAME
          value: "https://eks.integratepro.online"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 60
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 18

---
apiVersion: v1
kind: Service
metadata:
  name: pastefy-app
  namespace: production
  labels:
    app: pastefy-app
spec:
  type: ClusterIP
  selector:
    app: pastefy-app
  ports:
  - port: 80
    targetPort: 1337

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pastefy-ingress
  namespace: production
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:475641479654:certificate/b86bd892-ce79-46da-9215-b7046dfcdb58
spec:
  ingressClassName: alb
  rules:
  - host: eks.integratepro.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pastefy-app
            port:
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pastefy-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pastefy-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70