apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: production
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        secretRef:
          accessKey:
            name: awssm-secret
            key: access-key
          secretKey:
            name: awssm-secret
            key: secret-access-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-secrets
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: mariadb-secrets
    creationPolicy: Owner
  data:
  - secretKey: mysql-root-password
    remoteRef:
      key: eks-production/mariadb
      property: root-password
  - secretKey: mysql-password
    remoteRef:
      key: eks-production/mariadb
      property: user-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pastefy-secrets
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: pastefy-secrets
    creationPolicy: Owner
  data:
  - secretKey: mysql-password
    remoteRef:
      key: eks-production/mariadb
      property: user-password