grafana:
  adminPassword: admin123
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: gp3
  service:
    type: ClusterIP
  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472

prometheus:
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

defaultRules:
  create: true
