apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: alamin@integratepro.online
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              securityContext:
                runAsNonRoot: true
                runAsUser: 1001
                runAsGroup: 1001
                fsGroup: 1001
                seccompProfile:
                  type: RuntimeDefault
              containers:
              - name: acme-challenge-solver
                securityContext:
                  allowPrivilegeEscalation: false
                  runAsNonRoot: true
                  runAsUser: 1001
                  runAsGroup: 1001
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                    - ALL
                  seccompProfile:
                    type: RuntimeDefault